#ifndef VALQUIRIA_JOAO_VICTOR_HUGUENIN_LUCAS_PARENTE_PEDRO_LIPPI_QUESTAO2_OPERACOES_MATRIX_H
#define VALQUIRIA_JOAO_VICTOR_HUGUENIN_LUCAS_PARENTE_PEDRO_LIPPI_QUESTAO2_OPERACOES_MATRIX_H

#include <stdio.h>
#include <stdlib.h>

#define DIM 30

void lerMatriz(int mat[DIM][DIM]);

void espelhamentoMatriz(int mat[DIM][DIM]);

void imprimirMatriz(int mat[DIM][DIM]);

#endif //VALQUIRIA_JOAO_VICTOR_HUGUENIN_LUCAS_PARENTE_PEDRO_LIPPI_QUESTAO2_OPERACOES_MATRIX_H
